require 'rake/testtask'

namespace 'test' do
  desc 'Run acceptance tests'
  Rake::TestTask.new 'acceptance' do |t|
    t.test_files = FileList['test/acceptance/**_test.rb']
  end

  desc 'Run unit tests'

  Rake::TestTask.new 'unit' do |t|
    t.test_files = FileList['test/**_test.rb']
  end
end

task 'test' => %w(test:unit test:acceptance)

task 'build' do
  sh 'bundle install --deployment'
end

task 'default' => 'test'
